---
title: "Pseudo Random Number Generators in R"
site: bookdown::bookdown_site
documentclass: book
output:
  bookdown::gitbook: default
  # bookdown::pdf_book: default
---

# Motivation and Background

## Random Numbers!
What does it mean for a number to be "random"? Well, nothing actually, since any number on its own can be considered random. What I will be discussing in this tutorial is the concept of random **sequences** of numbers. Well what does it mean for a sequence of numbers to be random? In short it means you have no idea of what number will come next in the sequence; there are no patterns. We will look more closely on how to judge what makes one sequences more random than another later. 

Being able to produce random sequences of numbers is not just a cool trick but has important practical applications. Areas like weather simulation, physics simulations, cryptography, simulating games with probabilities, all rely on a proper way to represent a random chance of an event happening. In R any time you use a function like `runif()` it needs to create a "random" distribution of numbers that follow a uniform distribution. These are a few examples among the many of the importance of random number sequences.

## Types of Random Number Generators
Before we dive into the code, an important distinction to make is the difference between *true* random number generator and *pseudo* random number generator (PRNG). A true random number generator is one that utilizes some external input that we believe is random to create the sequence of numbers. Examples of these include using a Geiger counter to measure background radiation, measuring static from a TV, or even measuring the electron noise measured by a smartphone camera. For more information about those, check out [this](https://en.wikipedia.org/wiki/Hardware_random_number_generator) nice Wikipedia article.

The disadvantage to using these hardware random number generators, is that they are not very fast (at generating the sequence) and they are not *reproducable*. Plus, they require the extra hardware. Most of the time we don't need this "true" randomness and we can get away with a pseudo random number generator.

A PRNG is just an algorithm that, when given some initial conditions, produces a sequence of random looking numbers. They are pseudo-random because that sequence will eventually repeat itself. Most often in computer programming languages you will use something called a "seed" which sets the initial conditions of the algorithm. Then, using the same seed, you can successfully reproduce your pseudo-random sequence.


The rest of this tutorial will be focused on how these PRNGs are implemented and what makes one algorithim better than another statistically.







